import { Token } from "./types"

export const tokenList: Token[] = [
  {
    type: "currency",
    chainId: "56",
    tokenId: "561",
    name: "Realital Metaverse",
    ticker: "RETA",
    address: "0x829555f1197171D35Ec51C095E27b47A246aC6A6",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: ["nft", "game", "p2e", "retaverse"],
  },
  {
    type: "currency",
    chainId: "56",
    tokenId: "562",
    address: "0xd911375E7E9582c70fC98b1C6C2fBaad86f457ef",
    name: "Retawars GoldRose Token",
    ticker: "GRT",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: ["nft", "game", "p2e", "retaverse"],
  },
  {
    type: "nft",
    chainId: "56",
    tokenId: "563",
    ticker: "RETA-HEROS",
    logoImgSrc: null,
    ens: null,
    name: "RETA HEROS",
    address: "0x2A451ee1Ad93851Dd49084b3DFb08F5a189DB5a0",
    tags: ["nft", "game", "p2e", "retaverse"],
  },
  {
    type: "platform",
    tokenId: "000",
    name: "Bitcoin",
    ticker: "BTC",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "platform",
    tokenId: "001",
    name: "Ethereum",
    ticker: "ETH",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "currency",
    chainId: "1",
    tokenId: "11",
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    name: "Tether - Ethereum",
    ticker: "USDT",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "platform",
    tokenId: "002",
    name: "BNB",
    ticker: "BNB",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "currency",
    chainId: "1",
    tokenId: "12",
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    name: "USD Coin - Ethereum",
    ticker: "USDC",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "currency",
    chainId: "1",
    tokenId: "13",
    address: "0x1d2f0da169ceb9fc7b3144628db156f3f6c60dbe",
    name: "XRP - BNB Smart Chain",
    ticker: "XRP",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "currency",
    chainId: "56",
    tokenId: "560",
    address: "BUSD-BD1",
    name: "Binance USD - BNB Smart Chain",
    ticker: "BUSD",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "currency",
    chainId: "56",
    tokenId: "5699",
    address: "0xba2ae424d960c26247dd6c32edc70b295c744c43",
    name: "Dogecoin - BNB Smart Chain",
    ticker: "DOGE",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "currency",
    chainId: "56",
    tokenId: "56012",
    address: "0x3ee2200efb3400fabb9aacf31297cbdd1d435d47",
    name: "Cardano - BNB Smart Chain",
    ticker: "ADA",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
  {
    type: "platform",
    name: "Solana",
    tokenId: "003",
    ticker: "SOL",
    logoImgSrc: "",
    bio: "",
    ens: null,
    tags: [],
  },
]
